package com.example.bankapplicatopm.enums;

public enum CryptoCurrency {
    //https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=UAH,USD,EUR,CAD,CZK,HUF,CHF,AZN,PLN
    //    {
    //  "UAH": 3011263.54,
    //  "USD": 66390.37,
    //  "EUR": 62145.97,
    //  "CAD": 90584.6,
    //  "CZK": 1576488,
    //  "HUF": 7950151.45,
    //  "CHF": 60769.11,
    //  "PLN": 269802.95
    //}
    BTC,ETH,FDUSD,SOL,HBAR,PEPE,USDC,BNB,DOGE,XRP,USDT,BONK,WIF,SHIB,ENA,FLOKI,NEAR,ALGO,AVAX,ONDO,
    ADA,FET,WLD,LTC,RNDR,TONCOIN,RUNE,SUI,TIA,FIL,DOT,MATIC,ARB,LINK,GALA,ETHFI,ORDI,APT,OP,JTO,FTM,
    BCH,ICP,SEI,STX,MEME,BNX,JUP,CORE,VELO,INJ,W,MANTLE,TRX,CHZ,MAVIA,PENDLE,ATOM,ARKM,YGG,ONT,AR,ONGAS,
    AEVO,ETC,AGIX,APEX,MKR,ATA,THETA,JASMY,STETH,XLM,STATK,UNI,CFX,WBTC,STEEM,EOS,CKB,BIGTIME,NEO,COS
}
